security:
    password_hashers:
        App\Entity\Public\PublicUser: 'auto'

    providers:
        public_users:
            entity:
                class: App\Entity\Public\PublicUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: public_users
            user_checker: App\Security\PublicUserChecker
            login_throttling:
                max_attempts: 5
            form_login:
                login_path: public_login
                check_path: public_login
                enable_csrf: true
                default_target_path: public_home
            logout:
                path: _security_logout
                target: public_login
            custom_authenticator: App\Security\GoogleAuthenticator

    access_control:
        - { path: ^/alpha/access$, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/verify-otp$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/me$, roles: ROLE_PUBLIC_USER }
        - { path: ^/api/v1/me/favorites, roles: ROLE_PUBLIC_USER }
        - { path: ^/api/v1/me/addresses, roles: ROLE_PUBLIC_USER }

when@test:
    security:
        password_hashers:
            App\Entity\Public\PublicUser:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
